// ACTION TYPES
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const DELETE_PROUDUCT_FROM_CART = "DELETE_PROUDUCT_FROM_CART";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_INFORMATION = "PRODUCT_INFORMATION";
export const ADD_TO_CART = "ADD_TO_CART";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const HANDLE_SORT_BUTTON = "HANDLE_SORT_BUTTON";
export const HANDLE_EDIT_POST = "HANDLE_EDIT_POST";
